### ISSUE TITLE
Chapter-10 "example of a custom form not using database" YIELDS  (name 'DAL' is not defined)

### ISSUE THREAD

**Issue by JoeCodeswell** [nicozanf/py4web-doc#3]
Dear Nico,

I am trying to make a minimal app that uses a custom form. 

I am following your [simple example of a custom form not using database access](https://nicozanf.github.io/py4web-doc/en/dev/chapter-10.html#example) .

I got `NameError: name 'DAL' is not defined` .

I changed Line 1:

was: `from py4web import Session, redirect, URL`
now: `from py4web import Session, redirect, URL, DAL, Field`

The error has disappeared.

Love and peace,
Joe Dorocak

**Comment by nicozanf** [comment]
Thank you, Joe.

The problem is that you're using old, outdated dev documentation. Use
instead the master one at
https://nicozanf.github.io/py4web-doc/en/master/chapter-12.html

This should work much better!

cheers,
Nico

Il giorno sab 2 apr 2022 alle ore 20:21 Joe Dorocak aka Joe Codeswell <
***@***.***> ha scritto:
